/*
 * TWC_private.h
 *
 * Created: 3/16/2024 5:33:50 PM
 *  Author: Saed Abozied
 */ 


#ifndef TWI_PRIVATE_H_
#define TWI_PRIVATE_H_

#define TWI_STATUS_VALUE			(TWSR_REG&0XF8)
#define TWI_START_CONDITION_ACK			0X08
#define TWI_REP_START_CONDITION_ACK		0X10
#define TWI_SLAVE_ADDRESS_WRITE_ACK		0X18
#define TWI_SLAVE_ADDRESS_READ_ACK		0X40
#define TWI_MATER_DATA_TRANSMIT_ACK		0X28
#define TWI_MATER_DATA_RECIEVE_ACK		0X50
#define TWI_MATER_DATA_RECIEVE_NACK		0X58

#endif /* TWC_PRIVATE_H_ */